### ISSUE TITLE
Project Title

### ISSUE THREAD

**Issue by vanadgir** [grahambleon/DNDler#8]
Hello Grahambleon,
Thanks for adopting my project; that's really cool!
I just couldn't help but notice the utter butchering of the spelling, though. Is that something you think you can address, or will I need to involve my attorney?
Anyway, no rush, really great that you're doing this. Looking forward to what you got in store, Grahamble.
~ Varun

**Comment by grahambleon** [comment]
Hi Vanadgir,

Thank you so much for reaching out.  I understand where you're coming from and while I have the utmost respect for you and the original project that serves as inspiration for 'The DNDler', We at the DNDler team have no intention of altering the name.  The title of the original project 'Dindler' is just a little too close to 'Diddler' and we found it to be kind of a creepy word to say.  We've decided to go with   'The DNDler' as title because it both pays homage to your original project and is a nice portmanteau of the words 'DND' and 'Roller'.  Thank you for your feedback, I'll be closing this issue.

Warm regards,
-Graham G.
